name: GRTL
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2023.12.12=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.13=h7f8727e_0
  - pip=23.3.1=py39h06a4308_0
  - python=3.9.18=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - setuptools=68.2.2=py39h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - tzdata=2023d=h04d1e81_0
  - wheel=0.41.2=py39h06a4308_0
  - xz=5.4.5=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - aiohttp==3.9.3
      - aiosignal==1.3.1
      - alembic==1.13.1
      - annotated-types==0.6.0
      - anyio==4.2.0
      - asttokens==2.4.1
      - async-timeout==4.0.3
      - atpublic==4.0
      - attrs==23.2.0
      - black==24.1.1
      - certifi==2022.12.7
      - charset-normalizer==2.1.1
      - click==8.1.7
      - colorlog==6.8.2
      - comm==0.2.1
      - contourpy==1.2.0
      - cycler==0.12.1
      - dataclasses-json==0.6.4
      - debugpy==1.8.0
      - decorator==4.4.2
      - dgl==1.1.3
      - exceptiongroup==1.2.0
      - executing==2.0.1
      - exmol==3.0.3
      - filelock==3.9.0
      - flufl-lock==8.0.2
      - fonttools==4.48.1
      - frozenlist==1.4.1
      - fsspec==2023.4.0
      - gensim==4.3.2
      - greenlet==3.0.3
      - idna==3.4
      - importlib-metadata==7.0.1
      - importlib-resources==6.1.1
      - ipykernel==6.29.1
      - ipython==8.18.1
      - jedi==0.19.1
      - jinja2==3.1.2
      - joblib==1.3.2
      - jsonc-parser==1.1.5
      - jsonpatch==1.33
      - jsonpickle==3.0.2
      - jsonpointer==2.4
      - jupyter-client==8.6.0
      - jupyter-core==5.7.1
      - karateclub==1.3.3
      - kiwisolver==1.4.5
      - langchain==0.1.5
      - langchain-community==0.0.18
      - langchain-core==0.1.19
      - langsmith==0.0.86
      - levenshtein==0.24.0
      - mako==1.3.2
      - markupsafe==2.1.3
      - marshmallow==3.20.2
      - matplotlib==3.8.2
      - matplotlib-inline==0.1.6
      - mpmath==1.3.0
      - multidict==6.0.5
      - mypy-extensions==1.0.0
      - nest-asyncio==1.6.0
      - networkx==2.6.3
      - numpy==1.22.4
      - optuna==3.5.0
      - packaging==23.2
      - pandas==1.3.5
      - parso==0.8.3
      - pathspec==0.12.1
      - pexpect==4.9.0
      - picologging==0.9.2
      - pillow==10.2.0
      - platformdirs==4.2.0
      - prompt-toolkit==3.0.43
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pydantic==2.6.1
      - pydantic-core==2.16.2
      - pygments==2.17.2
      - pygsp==0.5.1
      - pyparsing==3.1.1
      - pystow==0.5.2
      - python-dateutil==2.8.2
      - python-levenshtein==0.24.0
      - python-louvain==0.16
      - pytz==2024.1
      - pyyaml==6.0.1
      - pyzmq==25.1.2
      - rapidfuzz==3.6.1
      - ratelimit==2.2.1
      - rdkit==2023.9.4
      - requests==2.28.1
      - scikit-learn==1.4.0
      - scipy==1.12.0
      - selfies==2.1.1
      - six==1.16.0
      - skunk==1.3.0
      - smart-open==6.4.0
      - sniffio==1.3.0
      - sqlalchemy==2.0.25
      - stack-data==0.6.3
      - sympy==1.12
      - synspace==0.3.0
      - tenacity==8.2.3
      - threadpoolctl==3.2.0
      - tomli==2.0.1
      - torch==2.2.0
      - torch-geometric==2.4.0
      - torchaudio==2.2.0
      - torchvision==0.17.0
      - tornado==6.4
      - tqdm==4.66.1
      - traitlets==5.14.1
      - typing-extensions==4.8.0
      - typing-inspect==0.9.0
      - urllib3==1.26.13
      - wcwidth==0.2.13
      - yarl==1.9.4
      - zipp==3.17.0
prefix: /home/szymon/anaconda3/envs/GRTL
